controller_list:
  - name: fake_ur_arm_controller
    joints:
      - ur_shoulder_pan_joint
      - ur_shoulder_lift_joint
      - ur_elbow_joint
      - ur_wrist_1_joint
      - ur_wrist_2_joint
      - ur_wrist_3_joint
  - name: fake_qbhand_controller
    joints:
      - qb_synergy_joint